# Generated by Django 3.2.6 on 2022-04-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_auto_20220428_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
