# Generated by Django 3.2.6 on 2022-04-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=15)),
                ('coin', models.CharField(max_length=15)),
                ('timeframe', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('position', models.CharField(choices=[('S', 'Sell'), ('B', 'Buy')], max_length=1)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('signal_at', models.DateTimeField()),
            ],
        ),
    ]
