# Generated by Django 3.2.6 on 2022-04-28 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='public',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='user',
        ),
        migrations.CreateModel(
            name='UserExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.CharField(max_length=300)),
                ('secret', models.CharField(max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.exchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
