# Generated by Django 3.2.6 on 2022-04-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userexchange_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchange',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.exchange'),
        ),
        migrations.AlterUniqueTogether(
            name='userexchange',
            unique_together={('name', 'user')},
        ),
    ]
